### ISSUE TITLE
Katuta Mwila hasn't replied to any emails yet!

### ISSUE THREAD

**Issue by EthanMaxwell** [EthanMaxwell/engr121-project3#2]

**Comment by sathiysuve** [comment]
Yeah, I guess we will just go on with the planning with whoever shows up and let Howard or Arthur know if she hasn't made any contact with us by the end of the week. what do you think?
Also, were you able to get in contact with Jaedan?

**Comment by EthanMaxwell** [comment]
Jaedan has responded twice to me so he is at least engaging a bit with the group.

**Comment by EthanMaxwell** [comment]
Also Howard said to email him if you couldn't get a group member to reply, but he was expecting us to do that four days ago! I can't imagine him being partially impressed if we are this slow to inform him of the situation....
